repos:
  - repo: local
    hooks:
      - id: system
        name: isort
        stages: [commit]
        entry: poetry run isort preql/
        types: [python]
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: black
        stages: [commit]
        entry: poetry run black preql/
        types: [python]
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: pylint
        stages: [commit]
        entry: poetry run pylint preql/
        types: [python]
        pass_filenames: false
        language: system
